#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Find the tracked GitHub certifications missing from a Credly profile."""

import argparse
import json
import os
import sys

from certifications import (
    fetch_user_certifications,
    normalize_badge_name,
    parse_credly_username,
)

DEFAULT_CATALOG_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    'certification_catalog.json',
)


def load_certification_catalog(catalog_path):
    """Load and validate the certification names generated by the rankings."""
    try:
        with open(catalog_path, 'r', encoding='utf-8') as catalog_file:
            data = json.load(catalog_file)
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f'Unable to read certification catalog: {error}') from error

    if not isinstance(data, dict):
        raise ValueError('Certification catalog must be a JSON object')

    certification_names = data.get('certifications')
    if not isinstance(certification_names, list) or not certification_names:
        raise ValueError('Certification catalog must contain a non-empty certifications list')
    if not all(isinstance(name, str) and name.strip() for name in certification_names):
        raise ValueError('Certification catalog contains an invalid certification name')

    return {normalize_badge_name(name.strip()) for name in certification_names}


def print_certifications(header, certification_names):
    """Print a sorted certification list under a count-bearing header."""
    print(f'{header} ({len(certification_names)}):')
    if not certification_names:
        print('  None')
        return
    for certification_name in sorted(certification_names):
        print(f'  - {certification_name}')


def console_symbol(symbol, fallback):
    """Return a status symbol that the active terminal can encode."""
    try:
        symbol.encode(sys.stdout.encoding or 'utf-8')
        return symbol
    except UnicodeEncodeError:
        return fallback


def main():
    """Run the missing-certification lookup command."""
    parser = argparse.ArgumentParser(
        description='Find tracked GitHub certifications missing from a public Credly profile.',
    )
    parser.add_argument('person', help='Credly username or public profile URL')
    parser.add_argument(
        '--catalog',
        default=DEFAULT_CATALOG_PATH,
        help='Path to a certification catalog JSON file',
    )
    args = parser.parse_args()

    try:
        username = parse_credly_username(args.person)
        catalog = load_certification_catalog(args.catalog)
    except ValueError as error:
        print(f'{console_symbol("❌", "ERROR:")} {error}')
        return 1

    print(f'{console_symbol("🔎", "LOOKUP:")} Fetching certifications for {username}...')
    obtained = fetch_user_certifications(username)
    if obtained is None:
        print(
            f'{console_symbol("❌", "ERROR:")} Credly data was incomplete; '
            'missing certifications were not calculated.'
        )
        return 1

    missing = catalog - obtained
    print()
    obtained_symbol = console_symbol('🏅', 'OBTAINED:')
    print_certifications(f'{obtained_symbol} Obtained tracked certifications', obtained)
    print()
    missing_symbol = console_symbol('🎯', 'MISSING:')
    print_certifications(f'{missing_symbol} Missing tracked certifications', missing)
    return 0


if __name__ == '__main__':
    sys.exit(main())